### PR TITLE
Commenting code and consistent formatting of JS.

### PR DESCRIPTION
**Pull request by jonathancross**
**_Style / code readability:**_
1. Single quotes for strings.
2. Two blank lines between methods.
3. White space.
4. Wrap at column 80.
5. Var names: websocket “address”  distinguished from bitcoin “address”.

**_Comments with JSDoc.**_
- Begin comments with capital letter, end with period.

### CODE REVIEW

**Comment by jonathancross** [comment]
I am not so familiar with Git, surprised to see 9beba00 here in the pull request - I was only trying to sync my fork with that pull request, so I would not expect any diffs there.

My actual changes are e636378.

Please advise if I need to redo this differently.

**Comment by caedesvvv** [comment]
maybe you need to update your fork with our master so the pull is already there?

**Comment by caedesvvv** [comment]
merged it anyways, lets see how it goes

**Comment by jonathancross** [comment]
Looks good to me.

**Pull request merged**
