### PR TITLE
 connect works again

### PR DESCRIPTION
**Pull request by zodman**
My local gateway never recive a connect.

With this it have a succesfull connect.

### CODE REVIEW

**Comment by caedesvvv** [comment]
Zodman, we need to debug this better, you changes are pretty random, in some cases breaking things and I don't see how they would fix anything if not by working around something else that might be broken....

**Comment by caedesvvv** [comment]
And @genjix please don't apply pull requests when you don't understand the implications.

**Comment by zodman** [comment]
what i break ? Darkwallet.core.connect() ? that not work on the controller.

**Comment by genjix** [comment]
sorry.
happy to assist on any small items or last minute bucket list. message me through irc.

**Comment by caedesvvv** [comment]
@zodman, sorry, the main problem is you introduce lots of changes. many of them are uneeded like making the controller add the url, when the controller is just to trigger a connect and doesn't provide an url since it already set the default connected and it intends to trigger a default connect...

I have been investigating too, and I see the problem is in the htm, everything else you changed was uneeded and adding superfluous code in that case doesn't help.

In the pull I interpreted more the other way around, you tried to do something in js that doesn't really changed much, also made some random html fix.

I tried the html fix, and it works but then starts with an empty row selected, would be great fix that, I see also with the "track by" the extra servers don't show up.

**Pull request merged**
